### ISSUE TITLE
Bump CNI plugin version to 0.9.0

### ISSUE THREAD

**Issue by abebars** [awslabs/amazon-eks-ami#1038]
**What would you like to be added**:
Bump CNI plugin version to v0.9.0

**Why is this needed**:
There is a bug fix for Stale UDP Connectors in v0.9.0 https://github.com/containernetworking/plugins/pull/553

**Comment by bwagner5** [comment]
Seems safe to update to v0.9.0 but we shouldn't upgrade past v1.0.0.  From what I understand, kubelet ships with a vendored libcni that is <1.0.0 in K8s 1.23 and below.  So it might be safe to update to v1.1.2 in K8s 1.24, but probably makes more sense to keep these uniform for now.

This update wouldn't affect the VPC CNI since it ships with the other CNI plugins it needs already.

**Comment by bryantbiggs** [comment]
ref #1308
