### ISSUE TITLE
Managed Node + Package Update

### ISSUE THREAD

**Issue by brnpimentel** [awslabs/amazon-eks-ami#1152]
Hi,

It's a simple question. WIth managed node, should package update (`yum update`) be run manually? Or AWS handle that?

I'm running a cluster with 3 nodes and AWS Inspector is showing vulnerabilities. I sshing into the node and it's showing packages that should be updated.

Thanks

**Comment by cartermckinnon** [comment]
Packages are not updated automatically on existing nodes. We release AMI's with the latest packages periodically; we currently aim to release twice a month. Generally, the most important patches will require a reboot of each node, requiring workload migration, etc. so the managed update operation (`UpdateNodegroupVersion`) is usually a better choice than rolling your own solution. Some users run custom AMI's in order to meet their specific security or compliance goals.

For many users, this is a reasonable balance between risk and operational reality; but your mileage may vary.
