### ISSUE TITLE
Build defaults should be for the golden path (containerd)

### ISSUE THREAD

**Issue by stevehipwell** [awslabs/amazon-eks-ami#1220]
**What would you like to be added**:
The current AMI build logic leaves runtime configuration required for the golden path (containerd) which could be the defaults when the image is built.

**Why is this needed**:
Use of the golden path should result in the quickest execution path with the least complexity.

**Comment by stevehipwell** [comment]
@cartermckinnon I don't think nodes using containerd should be running the expensive bootstrap commands and slowing down the node joining the cluster. So I'd like to see the nodes built for containerd and the modifications only happening at bootstrap to switch to Docker. This also impacts reliability as bootstrap modification logic is inherently more likely to ship with defects than the build logic which would fail and block the release.

Fundamentally systems should be optimised for the golden path and in this context the golden path is containerd.

The EKS v1.23 EOL is 7 months away so I don't think waiting until then is a good enough solution.

CC @bwagner5 I think this falls into what you were testing with Karpenter node creation.

**Comment by cartermckinnon** [comment]
> I don't think nodes using containerd should be running the expensive bootstrap commands and slowing down the node joining the cluster.

There's some stuff in [this block](https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L549-L592) that *could* be baked in at build time, instead of done at runtime, but I don't agree that it's having any meaningful impact on node bootstrap time.

> This also impacts reliability as bootstrap modification logic is inherently more likely to ship with defects than the build logic which would fail and block the release.

Not necessarily, we exercise the bootstrap logic extensively before AMI's are publicly released.

> Fundamentally systems should be optimised for the golden path and in this context the golden path is containerd.

I agree on principle, but in this case I don't see any performance benefit in making this change before 1.23 goes EOL; at which point we can do some more thorough cleanup.
