### ISSUE TITLE
Containerd restarts when provided with --containerd-config-file option on startup

### ISSUE THREAD

**Issue by thatInfrastructureGuy** [awslabs/amazon-eks-ami#1367]
**Environment**:
- AWS Region: us-west-2
- Instance Type(s): c5.2xlarge
- EKS Platform version : eks.3
- Kubernetes version : 1.27
- AMI Version:  amazon/amazon-eks-node-1.27-v20230711
- Kernel : 5.10.184-175.731.amzn2.x86_64
- Release information: Amazon Linux 2

**Questions**:

1. Providing `--containerd-config-file`  to bootstrap script restarts the containerd service after boot in 1.27.  I did not see this behavior in 1.22. Is this expected behavior in 1.27? ([According to this comment](https://github.com/awslabs/amazon-eks-ami/issues/610#issuecomment-1049737390), restarting containerd might cause kubelet to restart.)
1. In 1.22 I saw IPVS was enabled on node. On 1.27, IPv6 seems to be enabled, even tho I only use/see IPv4 IP addresses attached to the nodes. I am using aws-vpc-cni. Is IPVS disabled in 1.27?
1. Lastly, the boot times for 1.27 is around 20-25 seconds.  For 1.22, it is ~10 seconds. Please see attached logs.

Thanks in advance!
[1.22-redacted-instance-logs.txt](https://github.com/awslabs/amazon-eks-ami/files/12211311/1.22-redacted-instance-logs.txt)
[1.27-redacted-instance-logs.txt](https://github.com/awslabs/amazon-eks-ami/files/12211312/1.27-redacted-instance-logs.txt)

**Comment by cartermckinnon** [comment]
> Providing --containerd-config-file to bootstrap script restarts the containerd service after boot in 1.27. I did not see this behavior in 1.22. Is this expected behavior in 1.27? (https://github.com/awslabs/amazon-eks-ami/issues/610#issuecomment-1049737390, restarting containerd might cause kubelet to restart.)

The thing that's changed in recent AMI's is the `containerd` service unit is now enabled during the build process, so `containerd` will start at boot. If you specify a `containerd` config file to the bootstrap script, `containerd` has to be restarted for the config file to have any effect.

This won't cause the kubelet to be restarted, because the kubelet unit is enabled + started *after* this: https://github.com/awslabs/amazon-eks-ami/blob/master/files/bootstrap.sh#L628-L629
