### ISSUE TITLE
Please begin using a config file ASAP for kube-proxy

### ISSUE THREAD

**Issue by dawidmalina** [awslabs/amazon-eks-ami#149]
**What happened**:
`deprecated` log entries appears during kube-proxy startup

**What you expected to happen**:
Remove deprecated flag and migrate to config file

**How to reproduce it (as minimally and precisely as possible)**:
Run regular node and check kube-proxy logs

**Anything else we need to know?**:

**Environment**:
- AWS Region: `eu-central-1`
- Instance Type(s): `t3.large`
- EKS Platform version: `eks.1`
- Kubernetes version: `1.11`
- AMI Version: `ami-010caa98bae9a09e2`
- Kernel: `Linux ip-10-10-12-205.eu-central-1.compute.internal 4.14.88-88.76.amzn2.x86_64 #1 SMP Mon Jan 7 18:43:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /tmp/release` on a node):

```
W0111 11:35:10.730137       5 server.go:195] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
```

**Comment by tklovett** [comment]
For whoever picks up this work, please be careful to avoid any issues similar to issue #128, where Kubernetes uses different defaults when a `--config` file is used. I can't find any docs that explicitly say the values might be different, [since there is really any documentation at all](https://github.com/kubernetes/kubernetes/issues/50041)

Command line docs: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-proxy/
Config file "docs": https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kube-proxy/config/v1alpha1/types.go

**Comment by micahhausler** [comment]
For Kubernetes 1.10 and 1.11, the flags are deprecated, but still functional. For future versions of Kubernetes, we'll evaluate updating kube-proxy to a config file.

Since Kube-proxy isn't a value that is managed in the AMI, but is an EKS auto-applied resource, I'm going to go ahead and close this issue.

**Comment by dawidmalina** [comment]
I agree that this configuration is not managed inside AMI and I'm ok to close this topics here. Do you think I should open similar ticket but inside container-roadmap project?

**Comment by micahhausler** [comment]
Yes, container-roadmap would be great.
