### ISSUE TITLE
clusterCIDR not specified

### ISSUE THREAD

**Issue by dawidmalina** [awslabs/amazon-eks-ami#152]
**What happened**:
clusterCIDR not specified in kube-proxy

**What you expected to happen**:
Properly configure kube-proxy

**How to reproduce it (as minimally and precisely as possible)**:
Run regular node and check kube-proxy logs

**Anything else we need to know?**:

**Environment**:
- AWS Region: `eu-central-1`
- Instance Type(s): `t3.large`
- EKS Platform version: `eks.1`
- Kubernetes version: `1.11`
- AMI Version: `ami-010caa98bae9a09e2`
- Kernel: `Linux ip-10-10-12-205.eu-central-1.compute.internal 4.14.88-88.76.amzn2.x86_64 #1 SMP Mon Jan 7 18:43:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /tmp/release` on a node):

```
W0111 11:35:10.758645       5 proxier.go:311] clusterCIDR not specified, unable to distinguish between internal and external traffic
```

**Comment by micahhausler** [comment]
Setting this flag forwards inbound node traffic to Service IPs to the appropriate pods, and was added in kubernetes/kubernetes#24429. In EKS the `clusterCIDR` would be the VPC CIDR, and the [range is updatable](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html#vpc-resize). Since that range can be updated after cluster creation, this feature won't always work correctly if it is set at cluster creation. You are free to append this flag to your kube-proxy daemonset if you need that functionality, but unless this (external traffic arriving at a node with a Service IP destination) becomes a repeated feature ask, we won't be adding this by default. Additionally, you'd have to change src/dst check on your EC2 instances for that traffic to reach nodes in the first place

**Comment by dawidmalina** [comment]
I understand this use case. Thanks for the explanation I appreciate it.
