### ISSUE TITLE
Not able to run Non-Privileged Container

### ISSUE THREAD

**Issue by robinku07** [awslabs/amazon-eks-ami#159]
**What happened**:Unable to run non-privileged container by setting the --allow-privileged=false. Its showing Node Not Ready.
**What you expected to happen**:It should be working as CIS benchmarks are recommending that this option should be set to false.
**How to reproduce it (as minimally and precisely as possible)**:Just change in /etc/systemd/system/kubelet.service --allow-privileged=false
**Anything else we need to know?**:N/A
**Environment**: 
- AWS Region: us-east-2
- Instance Type(s): t3.medium
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): "eks.1"
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`):"1.11"
- AMI Version: ami-053cbe66e0033ebcf
- Kernel (e.g. `uname -a`):
- Release information (run `cat /tmp/release` on a node):ghh

```
```

**Comment by micahhausler** [comment]
The CIS recommendation around non-privileged containers suggest to use [PodSecurityPolicy](https://kubernetes.io/docs/concepts/policy/pod-security-policy/).
PodSecurityPolicy only became a beta feature as of Kubernetes 1.13, and EKS does not enable alpha features. Since EKS requires privileged containers to run CNI, I'm going to close this issue.
