### ISSUE TITLE
Cloud-init ignores package installation

### ISSUE THREAD

**Issue by petrzjunior** [awslabs/amazon-eks-ami#1842]
**What happened**:
I wanted to install additional packages with cloud-init. I added a packages to the `packages:` array in cloud-init yaml and applied. The package was not installed.

**What you expected to happen**:
I expect the cloud-init to install the packages as specified.

**How to reproduce it (as minimally and precisely as possible)**:
For example I wanted to install FIPS crypto policies in AL2023:
```yaml
#cloud-config
packages:
  - crypto-policies-scripts
```
The package was not installed. There is no log entry either.

**Anything else we need to know?**:
I think the package installation step always skipped, because there is no log entry. I suspect the following PR https://github.com/awslabs/amazon-eks-ami/pull/1074. `package-update-upgrade-install` was disabled in AL2 and later also in AL2023.

I am able to install the package manually
```sh
#cloud-config
runcmd:
  - dnf install -y crypto-policies crypto-policies-scripts
```
but this is error prone, sometimes the command fails due to race condition with other package manager-locking process.

**Environment**:
- AWS Region: eu-central-1
- Instance Type(s): r7a.large
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.13
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1:28
- AMI Version: amazon-eks-node-al2023-x86_64-standard-1.28-v20240605

**Comment by cartermckinnon** [comment]
We disabled `package-update-upgrade-install` for a few reasons -- we've seen many cases where installing the latest version of a package in your prod environment causes outages; and there often is no rollback mechanism in place that can mitigate it. You inevitably end up with a mix of package versions across your nodes, which can introduce hard-to-debug differences in behavior. There's the added time spent warming the package repo cache, even if nothing is ultimately installed/updated. There's also the availability risk if the remote repository is having issues. The safest approach is to bake all your packages into an AMI (and test it!), so that your prod environment stays deterministic. YMMV, and you know your use case better than we do -- but that's why our defaults are what they are.
