### ISSUE TITLE
[k8s>=1.30] switch off NodeSwap feature gate for AL2 based images

### ISSUE THREAD

**Issue by dims** [awslabs/amazon-eks-ami#1868]
As of https://github.com/kubernetes/kubernetes/pull/122745, `NodeSwap` has been switched to `true` by default. Since we know that `NodeSwap` works only with cgroupv2 and AL2 defaults to cgroupv1, can we switch off the feature gate?

See https://github.com/kubernetes/test-infra/pull/32876 for context where we had to do this to ensure CI jobs are stabilized with AL2.

cc @cartermckinnon @njtran

**Comment by cartermckinnon** [comment]
We'd need to add some logic for older (and future) k8s versions where the feature flag doesn't exist, and since using swap requires you to also disable `failOnSwap` *and* configure the swap volumes, I'm not sure it makes sense to have this additional guardrail/callout. @ndbaker1 what do you think here?

**Comment by ndbaker1** [comment]
> add some logic for older (and future) k8s versions where the feature flag doesn't exist

we don't need to do anything for older version right?  

If we already had logic in place to enforce `NodeSwap=false` it would make a lot of sense, but it sounds like the default makes sense from the PR since it won't be configures as `NoSwap`

I'm also not eager to track more featureGates besides the ones we currently set (which are all related to credentials afaict)

**Comment by cartermckinnon** [comment]
> we don't need to do anything for older version right?

the feature gate was added in 1.22, so we can't specify it for 1.21 or kubelet will complain. When the feature gate is removed in the future, we'll have to come back and add a check for that boundary as well

> If we already had logic in place to enforce NodeSwap=false it would make sense, but sounds like the default from the PR is NoSwap which works as expected?

yeah that's my thinking, the feature gate default changing was a no-op anyway, since you have to opt-in with several other config options

**Comment by cartermckinnon** [comment]
I think we'll leave things as-is for now
