### ISSUE TITLE
How to use max-pods-calculator.sh to set maxPods in AL2023

### ISSUE THREAD

**Issue by shra1-fb** [awslabs/amazon-eks-ami#1902]
**Environment**:
- AWS Region: us-west-2
- Instance Type(s): t3.medium
- EKS Platform version: eks.13
- Kubernetes version: 1.28
- AMI Version: eks.v1_28.al2023

In AL2, there was a way to run max-pods-calculator.sh script in user data as it was available in AL2 runtime (https://github.com/awslabs/amazon-eks-ami/blob/main/templates/al2/runtime/max-pods-calculator.sh). This isnt the case in AL2023, what's the recommended way to calculate max-pods for an instance type in AL2023?

**Comment by wasd171** [comment]
This script was also quite convenient for us, is there an alternative for AL2023?

**Comment by snorlaX-sleeps** [comment]
Since we needed to work this out recently and I couldn't find it anywhere else:
`maxPods` is now available in the kubelet-config and is available during the userdata execution, before the node connects to the cluster. This is now added by nodeadm on instance start, rather than having to read it from a file.

`MAX_PODS=$(jq '.maxPods' "/etc/kubernetes/kubelet/config.json")`

[Apparently where it comes from](https://github.com/awslabs/amazon-eks-ami/blob/main/nodeadm/internal/kubelet/eni-max-pods.txt)
