### ISSUE TITLE
Iptables rules in kubelet.service

### ISSUE THREAD

**Issue by SMR39** [awslabs/amazon-eks-ami#332]
Hello,

I was trying to understand the need for having this iptables rule here. https://github.com/awslabs/amazon-eks-ami/blob/master/files/kubelet.service#L8 

If this was introduced to fix docker trying to change rule from ACCEPT to DROP then I think this was indeed fixed in https://github.com/kubernetes/kubernetes/issues/59656 and that line can be removed to avoid further confusions.

**Comment by mogren** [comment]
I do think we should verify this. The change seems to be

https://github.com/kubernetes/kubernetes/pull/62007/files#diff-97649d13432b01b4e7669d728a2e2e82R1324-R1329

**Comment by GnatorX** [comment]
An update on the issue I raise. It seems like, for us, an iptable save was performed prior to startup of the node which meant we saved FORWARD DROP. On startup, since kubelet and iptable restore happens around the same time, we run into a race condition where FORWARD DROP may be applied over FORWARD ACCEPT if iptable restore after kubelet start.

**Comment by yongzhang** [comment]
I have another question, in https://github.com/awslabs/amazon-eks-ami/blob/v20210830/scripts/install-worker.sh#L99, I'm curious why only a copy there without starting the service? How the service been started?

**Comment by yongzhang** [comment]
> I have another question, in https://github.com/awslabs/amazon-eks-ami/blob/v20210830/scripts/install-worker.sh#L99, I'm curious why only a copy there without starting the service? How the service been started?

Sorry, found it in `bootstrap.sh`.

**Comment by hovo972** [comment]
Is it a really good idea to have a move here https://github.com/awslabs/amazon-eks-ami/blob/v20210830/scripts/install-worker.sh#L99 (as opposed to having a copy)?

It cost me a day to figure out why re-running bootstrap.sh was failing to start my cluster :/

**Comment by cartermckinnon** [comment]
I don't know why this was added in #90, I think the reviewers overlooked it. It's not clear to me why this would be necessary, as components like `kube-proxy` that rely on iptables rules should be managing those themselves.

@nithu0115 was the author, who might be able to provide more info. Otherwise, I'll try removing it when I have some time.
