### ISSUE TITLE
Add complete Kubernetes version in CHANGELOG.md

### ISSUE THREAD

**Issue by bhavin192** [awslabs/amazon-eks-ami#339]
**What would you like to be added**:
It will be great if we add complete Kubernetes version i.e. `major.minor.patch` to the `CHANGELOG.md` file as well in the release note. Will be awesome if we can add it to the AMI name as well.

**Why is this needed**:
The only way to get the version and date is the `Makefile`. But this file will be update as we do a new release. `kubernetes_build_date` and the `kubernetes_version` are required to build the AMI. Having those in `CHANGELOG.md` and release notes will make it easy to find out and build custom AMI.

For example, I want to build AMI for this release https://github.com/awslabs/amazon-eks-ami/releases/tag/v20190906 but I don't know what should be the `kubernetes_version` for 1.12, 1.13 and so on.

**Comment by tonyflint** [comment]
This is confusing for me too; why is the [Makefile](https://github.com/awslabs/amazon-eks-ami/blob/master/Makefile#L49) not updated to reflect the `kubernetes_version` and `kubernetes_build_date` used to generate the official AWS EKS AMI that corresponds to the latest release?

**Comment by M00nF1sh** [comment]
@tonyflint 
Hi, we have an internal pipeline with configurations for the `binary_bucket_name` and `kubernetes_build_date`. And the pipeline is building AMIs with `make k8s binary_bucket_name=${} kubernetes_build_date=${}` instead of these `make 1.11`.
I think it's better to publish latest bucket as an SSM parameter instead of manually updating this file is better(which is hard to automate)

**Comment by mmerkes** [comment]
I believe that this issue is now resolved. The changelog includes the kubernetes full version and the build date of the binaries used, like this: `s3://amazon-eks/1.19.6/2021-01-05/`, which would be converted to a command like this: `make k8s kubernetes_version=1.19.6 kubernetes_build_date=2021-01-05 pull_cni_from_github=true`.

As for the AMI ID, that information can be found [here](https://docs.aws.amazon.com/eks/latest/userguide/eks-optimized-ami.html) for the latest version.

If you asking for additional info, please open a new issue with the details.
