### ISSUE TITLE
Building the current master branch in eu-west-1 results in an unusable AMI

### ISSUE THREAD

**Issue by janbeerden** [awslabs/amazon-eks-ami#406]
**What happened**:

1. The AMI does not use the latest release binaries, 1.14.6/2019-08-22 instead of 1.14.8/2019-12-13 as specified in the latest release notes.

2. Also the kubelet config references an aws-iam-authenticator "region" flag that is currently not been released yet. This prevents the kubelet from registering the instance with the control plane.
```
kubelet: Error: unknown flag: --region
kubelet: Usage:
kubelet: aws-iam-authenticator token [flags]
``` 
As far as I can see, the `region` flag is introduced in v0.5.0-alpha.1 of aws-iam-authenticator and v0.4.0 is being used in the AMI.

**What you expected to happen**:

1. An AMI that has the latest 1.14.8/2019-12-13 (or newer) binaries
2. A working version of aws-iam-authenticator or a working kubeconfig so the kubelet starts without errors.

**How to reproduce it (as minimally and precisely as possible)**:
1. Build a 1.14 AMI in eu-west-1 (so both aws_region and binary_bucket_region are set to eu-west-1)
2. Start an instance in eu-west-1 based on the newly created AMI

**Anything else we need to know?**:
We added some extra's to the Makefile and install-worker.sh script, but nothing that touches anything related to the issues described above.
Our previous build, based on https://github.com/awslabs/amazon-eks-ami/commit/81ac166912ebbdb46c56549efe3d88331f524cad, with the same minor additions, did work as expected.

**Environment**:
- AWS Region: eu-west-1
- Instance Type(s): n/a
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks.6
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.14
- AMI Version: n/a
- Kernel (e.g. `uname -a`): 4.14.158-129.185.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):

```
n/a
```

**Comment by janbeerden** [comment]
Apparently https://github.com/awslabs/amazon-eks-ami/pull/388 already addresses the binary version issue, however the latest AMI release does not appear to be in sync with git.

**Comment by M00nF1sh** [comment]
@janbeerden 
Please don't use master branch to build AMIs, always use the tagged ones.
The master branch requires an new aws-iam-authenticator due to https://github.com/awslabs/amazon-eks-ami/pull/398. 
We have an internally staged binaries(but haven't published due to our release schedule), I'll try to get it published asap before we actually release the AMI itself

Also, we can use the `make k8s kubernetes_version=xxxx kubernetes_build_date=xxxx` directly instead of `make 1.14` to use newer binaries. (However, i do agree we should update this makefile to point to newer binaries whenever we published new ones)

**Comment by janbeerden** [comment]
@M00nF1sh , thank you for clearing things up and giving some additional insights.

Since I am more accustomed to using git flow, I thought the master branch would be a stable starting point. But I understand that this is not the case here.

I am curious, how would a critical bug/security fix fit in to all this?

**Comment by M00nF1sh** [comment]
@janbeerden 
we have an internal-only S3 bucket for staging binaries(kubelet/authenticator), and our pipeline runs against that internal S3 bucket. Bugs fixes and security fixes go there. (That's why we only released binaries to amazon-eks bucket after we released the AMI before, since we also need testing to verify the ami works fine before we release the binaries).

Also, our pipeline runs against an internal-clone of this amazon-eks-ami repo(currently it's using same commit as this public one), but we do have the ability to switch to an private bugFix branch if there are securities fixes need to be done in this repo :D

**Comment by janbeerden** [comment]
@M00nF1sh , okay time to update our own build process to start from a release tag.

Is there place we can find the latest Kubernetes version and build date to use with make? Aside from the release notes.

**Comment by M00nF1sh** [comment]
The current best way is to do `aws s3 ls s3://amazon-eks/` to figure it out. I think it's a good idea to put it as an SSM parameter or create an index file somewhere to enable programmatic access.

**Comment by davidygs** [comment]
We have an issue, in which the node groups in our `ap-northeast-1` eks cluster keeps hitting the global sts endpoint instead of the regional one. I assume #398 would fix the problem, correct? If so, any timeline as to when the updated ami will be available?

**Comment by M00nF1sh** [comment]
@davidygs Yes, it's currently in pipeline waiting for sign-off(waiting for new region launch). it's expected to be released in a week or so, let me see whether i can push it to release for other regions first.

**Comment by davidygs** [comment]
@M00nF1sh Should we following [this doc](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#aws-sts) and make sure to set `AWS_STS_REGIONAL_ENDPOINTS=regional` in the new AMI so that we are actually the regional sts? Looks like both the go and python SDKs default to use the global endpoint ([here](https://github.com/aws/aws-sdk-go/blob/81e3e85a4c468e37c10c240c6ec85ac99bb6aac1/aws/session/session.go#L562) and [here](https://github.com/boto/botocore/blob/5d06293532ef9f61f49b38b24998584a49668666/botocore/configprovider.py#L88)).

**Comment by M00nF1sh** [comment]
@davidygs If you build an ami with v0.5.0 authenticator, and pass-in region https://github.com/awslabs/amazon-eks-ami/blob/master/files/kubelet-kubeconfig#L24, you don't need to.
I didn't a change in v0.5.0 authenticator to always use regional sts if `--region` is passed: https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/283

**Comment by davidygs** [comment]
@M00nF1sh Ok, that makes sense. 

In the meantime, we are using `eksctl` to manage our eks cluster. The [eksctl kubeconfig](https://github.com/weaveworks/eksctl/blob/9cf9122e46817e2113927f9e695081e85ef68fdd/pkg/utils/kubeconfig/kubeconfig.go#L103) will probably need to be updated to reach parity with #283 in order for `eksctl` users to take advantage of the new `--region` flag in the updated authenticator. 

I didn't look but maybe a PR has already been start on that end?

**Comment by M00nF1sh** [comment]
@davidygs I'll find someone on our endpoint to work on eksctl :D.
seems they have to use AWS_STS_REGIONAL_ENDPOINTS and AWS_DEFAULT_REGION.

**Comment by mogren** [comment]
This issue has been resolved. Please open a new ticket if a newly built AMI is broken in any way.
