### ISSUE TITLE
Anyway to make the boot of a new node faster?

### ISSUE THREAD

**Issue by t0ny-peng** [awslabs/amazon-eks-ami#417]
**Environment**:
- AWS Region: us-west-2
- Instance Type(s): c5.18xlarge, spotinstance
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): eks4
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): 1.14
- AMI Version: Latest
- Kernel (e.g. `uname -a`): 
- Release information (run `cat /etc/eks/release` on a node):

```
```

We are using spot instance to handle the fluctuating load. However, it takes about 2:25 for a new node to start, join the cluster and start taking pods. 

Is there any dark magic to shorten the booting process? 

Thanks

**Comment by mogren** [comment]
Hi @left4taco, the CNI might affect this a bit. Since v1.5.3, we wait with marking the node as "Ready" in Kubernetes by delaying the copying of the CNI plugin binary and config file until after ipamd has managed to talk to the Kubernetes API server, and also attach secondary IPs on the primary ENI. The reason for this is that we don't want to have nodes marked as ready if there are no IPs available on them. If we did that, pods would start to get scheduled on the node but be unable to start.

You might want to try tweaking the default readiness-probe timeout of 35 s (At least in the v1.6.0 config) to something lower, and maybe the frequency to less than 10s as well. That might save you some time. Also, if you start a lot of these at the same time, v1.6.0 will use less EC2 calls to get started. This is important since the EC2 control plane will throttle the requests if they get too many at the same time.

**Comment by tibin-mfl** [comment]
@mogren 
If I am right EKS optimized Linux image already uses minimal OS amzn2-ami-minimal-*.
Does any other minimal OS like bottle-rocket or CoreOS help us here, to reduce the boot time?

**Comment by cartermckinnon** [comment]
EC2 provisioning times depend on current load and instance availability. You may be interested in [Karpenter](https://github.com/aws/karpenter), which handles EC2 provisioning and pod assignment, eliminating k8s scheduler and EC2 auto-scaling group lag. Karpenter can also help you optimize your EC2 spend by allocating appropriately-sized instances for your current workload.

**Comment by rshad** [comment]
I think the solution, in this case, is to use the Warm Pools, in which you'd have instances already created and in a stopped or hibernated state and so, when these are triggered to be started it'd take way less time than when the instance has to be created from 0, but unfortunately, the Kubernetes Cluster Autoscaler still not interacting with this new AWS feature yet.

- https://github.com/kubernetes/autoscaler/issues/4005
- https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-warm-pools.html
