### ISSUE TITLE
EKS-Optimized AMI with GPU Support

### ISSUE THREAD

**Issue by max-rocket-internet** [awslabs/amazon-eks-ami#45]
Just a few questions around the [AMI with GPU support](https://docs.aws.amazon.com/eks/latest/userguide/gpu-ami.html):

1. Is this AMI built from this repo too? If not, where from?
2. Does the AMI with GPU support use `/etc/eks/bootstrap.sh` also?

**Comment by hmizuma** [comment]
1. Sorry, the build for AMI with GPU support is not open source at this time. Please subscribe through AWS marketplace https://aws.amazon.com/marketplace/pp/B07GRHFXGM.
2. Yes, the AMI with GPU support uses the same `/etc/eks/bootstrap.sh`.

**Comment by micahhausler** [comment]
Closing with @hmizuma's answer

**Comment by wskinner-eml** [comment]
Is there a timeline to support this?

**Comment by micahhausler** [comment]
@wskinner-eml not at this time. The reason for not OSSing the GPU AMI changes is that customers have to agree to an EULA to launch and use the GPU AMI.

**Comment by codytubbs** [comment]
@micahhausler I wanted to check in and see if the consensus is still no plans?

Getting past the EULA in automated fashion simply requires passing the `--silent` (advanced option) to the NVIDIA/CUDA run builder(s) (if installing that way), and having a copy of the EULA which gets dropped in /etc/eks/nvidia-eula. Both seems fairly trivial in regards to choosing to keep the install-worker.sh (or maybe install-gpu-worker.sh ?:) private from folks.

In my case, at work and elsewhere, it's crucial we have the ability to source how AMIs are built via OSS/openly available build scripts and such that detail (at the least by viewing the scripting) all of the 3rd party locations they may be grabbing packages, libs, plugins, etc. from so that if we need to update our suite of images due to a security concern, we are able to do so. As well as do our due diligence and triple check that the authors of the AMIs are doing proper things like checking hashes (from more than one source), etc. Especially when we're dealing with a larger amount of binaries than usual with these EKS* builds.  Also, with all of those binaries, they must be tracked down, versioned, etc. and when we can't see how they're pulled in, we can't get the meta from the package managers that show the source. e.g. `yum -qf', `rpm -S', etc. will simply return nil package, which is extremely concerning to sec engineers, and should be as well for everyone else on the planet. :)

Without the ability to do the above, we cannot source the AMIs and process them through our hardening pipeline(s).
And in this particular case with the GPU version of the EKS AMI, where we have not been able to reliably trust the closed source builds, I've had to resort to building both, the EKS and EKS+GPU AMIs from nearly scratch, using our hardened ubuntu18.04 base image.  Don't get me started on how badly kept the (latest) Conical EKS AMI is -- super old versions of docker being pinned (from 2017), still bridging docker0, etc.

With that said, as of today, and after a few weeks of work (mainly due to the inherent time for every packer build and cluster creation+cfn teardown to complete), I've successfully combined the EKS and EKS+GPU build work into a single image that works in either use-case, no longer needing the non-gpu image.  I'm not sure why two images are still being maintained (or partially maintained? --(it's been over 365 days since the master/CHANGELOG.md has been updated:( ).
With the oci-add-hooks source and a few other blatant requirements, it (assumingely) seems fairly simply to add the additions from a `diff -u install-worker.sh install-gpu-worker.sh` on yall's side.

Pretty please pitch us something better than EULA as the reason.  I'd like to prevent wasting several weeks of my time in the future due to another AWS related choice like this.   After reading so many threads of other folks interested in hardening their aws/labs images, it just seems like there's a major gap and disconnect over there that's not understanding the seriousness of (massively huge) companies and sec teams needing to vet images.  This includes the OSS stacked on top of trusted base images (line by line at times) and then keeping them hardened ourselves, while also having to reliably build trust (by way of keeping (sometimes extensive) track records of flawlessly* built images and the team(s) who have built them until the risk goes from unknown aka extremely high, to hopefully (extremely) low.
This can only happen after sec teams can vet the build code, release after release, and rely on predictably reliable release lifecycle(s), which can only be done after a great track record is kept up, partially by way of images that have characteristics that include being 100% CVE-free, have 0% failed hash checks or hash checks based on a single provider of the hash, or straight up nil checks, especially for all of the 3rd party (and binaries) the EKS and non-sec portions of the k8s community seems to turn a blind eye on for the trade-off of all that is good that k8s provides.

Sadly I'll be doing the same with Neuron support next.  I can't get over all of the closed source and undocumented repos that packages and binaries get pulled from as well.  Like I said, there's a total disconnect somewhere, possibly starting with the SSDLC leads and OSS champions.  For all we know it's a sales decision, if we read into the first response on this issue above. :(

I'm disappointed (amid many others) that Conical nor the awslabs team can completely release the source for what it takes to build the current images they are sharing for folks to download and use for EKS and accelerated EKS with GPU support.

Random Q... when did the al2 based images that get published for EKS diverge from the source that's in the amazon-eks-ami repo?  One can only assume around the last time the repo Changelog.md was updated. :\ -- there are definitely differences in the repo and what's on the images IIRC.

Cheers,
-CT
