### ISSUE TITLE
Give EKS nodes the ability to resolve in-cluster dns

### ISSUE THREAD

**Issue by garthwilliamson** [awslabs/amazon-eks-ami#509]
**What would you like to be added**:

The ability for nodes to resolve cluster.local addresses. There are numerous tickets about this on github (e.g. https://github.com/kubernetes/kubernetes/issues/44528) however I couldn't find one specifically for EKS.

**Why is this needed**:

When hosting NFS or an image registry within the cluster, the docker daemon uses the nodes dns resolution to find these things. If the nodes could look up cluster.local addresses using coredns, NFS shares and images could be specified using proper service names instead of workarounds.

** Workaround**:

We are thinking about using fixed clusterip addresses instead, however this requires maintaining a database of addresses in use externally.

**Comment by cartermckinnon** [comment]
After reading the linked issue, there are suggestions for use cases like NFS (the NFS CSI driver) and others (Kubernetes mechanisms like `ExternalName`). This seems like something that should be designed for and handled at the Kubernetes level, not on the nodes; so that the behavior is consistent across providers.
