### ISSUE TITLE
Why do I need to specificy kubernetes_version/kubernetes_build_date when building a specific target?

### ISSUE THREAD

**Issue by grayaii** [awslabs/amazon-eks-ami#524]
This is really a noob question, but I just did this:
export SOURCE_AMI_ID=XXXXX
export AWS_ACCOUNT_ID=YYYYY

$ make k8s 1.17
packer validate  --var aws_region='us-west-2'  --var ami_name='amazon-eks-node-.-v20200814'    --var binary_bucket_region='us-west-2'              --var arch='x86_64'  --var instance_type='m4.large'       eks-worker-al2.json
Error initializing core: 2 error(s) occurred:

* required variable not set: kubernetes_version
* required variable not set: kubernetes_build_date

Why is asking for the version and build date, if I'm already specifying I am building 1.17 via the make command?

By specificying "make k8s 1.17", shouldn't the make file automatically set the correct kubernetes_version and kubernetes_build_date

Sorry, it's my first time following the build instructions here:
https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/

**Comment by omnibs** [comment]
It seems both are necessary to download binaries from a public s3 bucket. Those variables feed into the bucket path, like `s3://amazon-eks/${kubernetes_version}/${kubernetes_build_date}/bin/linux/amd64/`.

Requires a bit of trial and error and a bit of `aws s3 ls`. Docs could be clearer I guess.

**Comment by mmerkes** [comment]
Looks like the command is wrong in the instructions you reference. Should be `make 1.17` if you're not specifying a specific build date. As @omnibs mentions, it's used to construct the S3 path. There are multiple build dates because as new patches are pulled into a specific version, a new build with a new build date gets created. Those instructions should definitely be more clear and I'll send the below feedback on that page. However, IMO, the README for this repo would be the best place to put the documentation on how to use this tool. I'll create an issue to track that.

The [referenced post](https://aws.amazon.com/premiumsupport/knowledge-center/eks-custom-linux-ami/) could be more explicit about how to get the versions and build dates:

*Existing*

```
1.    To examine the available binaries provided in the default bucket, run the following AWS Command Line Interface (AWS CLI) command:

$ aws s3 ls s3://amazon-eks 
$ aws s3 ls s3://amazon-eks/kubernetes_version/kubernetes_build_date/bin/linux/arch/
Note: Replace amazon-eks, kubernetes_version, kubernetes_build_date, and arch with your values.
```

*Improved*

```
1.    To examine the available binaries provided in the default bucket, run the following AWS Command Line Interface (AWS CLI) command:

Get a list available Kubernetes versions:

$ aws s3 ls s3://amazon-eks 
$ KUBERNETES_VERSION=1.17.9 # Or different version

Get a list of build dates:

$ aws s3 ls s3://amazon-eks/$KUBERNETES_VERSION/
$ KUBERNETES_BUILD_DATE=2020-08-04 # Or different value

Get a list of platforms:

$ aws s3 ls s3://amazon-eks/$KUBERNETES_VERSION/2020-08-04/bin/
$ PLATFORM=linux

Get a list of architectures:

$ aws s3 ls s3://amazon-eks/$KUBERNETES_VERSION/2020-08-04/bin/linux/
$ ARCH=amd64
```

This command doesn't work:

```
2.    To trigger the build process by providing the Kubernetes version as the parameter, run the following command:
$ make k8s 1.14  # Build a Amazon EKS Worker AMI for k8s 1.14
```

Should be:

```
make 1.14
```

While we're updating it, we should reference [the latest available version](https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html).

**Comment by mmerkes** [comment]
Closing this issue in favor of the issue created above.
