### ISSUE TITLE
Containerd v1.5 support?

### ISSUE THREAD

**Issue by vavdoshka** [awslabs/amazon-eks-ami#800]
**What would you like to be added**:

Update Containerd version to  v1.5
I did not find any roadmap or existing Issue on that so I wonder if this is something planned and what is the scope of the changes.

**Why is this needed**:

In particular for me the trigger to this question was this functionality added in 1.5 - https://github.com/containerd/containerd/blob/main/docs/hosts.md

**Comment by smothiki** [comment]
Adding to this containerd 1.5.8 version should be picked as it has lot of CVE patches that current version is missing 1.4.6. 

https://github.com/opencontainers/distribution-spec/security/advisories/GHSA-mc8v-mgrf-8f4m
https://github.com/opencontainers/distribution-spec/security/advisories/GHSA-mc8v-mgrf-8f4m
https://github.com/advisories/GHSA-c2h3-6mxw-7mvq

These are very critical issues and have been fixed in 1.5.8. Would be really helpful and make EKS contained secure if these contained is upgraded

**Comment by bubeamos** [comment]
Any updates yet ?  1.5.X + of containerD is really needed seeing as the issue reported [here](https://github.com/containerd/containerd/issues/4604#issuecomment-1027293621) is fixed in this version.

**Comment by aquam8** [comment]
We are also very keen to see AMI for EKS released with version 1.5x of containerd - especially knowing that 1.23 on EKS will come with `containerd` as default runtime.
🙏

**Comment by smothiki** [comment]
Hey tea, Any update on this?

**Comment by universam1** [comment]
Consider upgrading to 1.6 instead, because of the performance issue in 1.5 branch: https://github.com/containerd/containerd/pull/6843

**Comment by robonilha** [comment]
Any updates? We need registry configuration in order to upgrade our clusters which is supported starting on v1.5

**Comment by cartermckinnon** [comment]
We're working on an update to 1.6 -- we expect that version to be available to us soon.

**Comment by zoramthanga** [comment]
We've also run into https://github.com/containerd/containerd/issues/4604, so upgrading to containerd 1.6 would be very appreciated.
