### ISSUE TITLE
Are DEP and ASLR Enabled?

### ISSUE THREAD

**Issue by scinerio** [awslabs/amazon-eks-ami#835]
This is just a general questions for compliance concerns. I was wondering if DEP/ASLR are enabled for this AMI. If not, how would one enable it? 

Thanks for the help!
Jason

**Comment by cartermckinnon** [comment]
I believe "DEP" is a Windows-specific term, this is usually referred to as "NX" for Linux and other systems. I don't know the answer for our Windows AMI's (which are not part of this repository). The AMI defined in this repository is built on Amazon Linux.

My understanding is that these are standard Linux kernel features (since version 2.6.x). LWN has some background (from 2011) regarding the series of patches that introduced it: https://lwn.net/Articles/422487/
