### ISSUE TITLE
v20220406 (latest) vulnerable to CVE-2022-1015, CVE-2022-1016, CVE-2022-25636

### ISSUE THREAD

**Issue by szymonpk** [awslabs/amazon-eks-ami#897]
**What happened**:

The latest image is vulnerable to CVEs CVE-2022-1015, CVE-2022-1016, CVE-2022-25636. It is part of important severity [ALAS2KERNEL advisory](https://alas.aws.amazon.com/AL2/ALASKERNEL-5.4-2022-024.html).

**What you expected to happen**:

Have patched image from AWS.

**How to reproduce it (as minimally and precisely as possible)**:

Boot up a node with the latest image.

**Anything else we need to know?**:

It is impossible to build a custom image because of https://github.com/awslabs/amazon-eks-ami/issues/896.

**Environment**:
- AWS Region: us-east-1
- Instance Type(s): n/a
- EKS Platform version (use `aws eks describe-cluster --name <name> --query cluster.platformVersion`): 1.19
- Kubernetes version (use `aws eks describe-cluster --name <name> --query cluster.version`): n/a
- AMI Version: v20220406
- Kernel (e.g. `uname -a`): `Linux ip-10-0-10-222.ec2.internal 5.4.181-99.354.amzn2.x86_64 #1 SMP Wed Mar 2 18:50:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Release information (run `cat /etc/eks/release` on a node): n/a

**Comment by abeer91** [comment]
Hello, thanks for filing an issue. 

For security issues or concerns, please do not open an issue or pull request on GitHub. Please report any suspected or confirmed security issues to AWS Security https://aws.amazon.com/security/vulnerability-reporting/

I'm going to close this issue.

**Comment by webframp** [comment]
@abeer91 Sorry, but this seems like the wrong response here. Besides being unhelpful, there's already an advisory https://alas.aws.amazon.com/AL2/ALASKERNEL-5.10-2022-012.html (linked to by the author) which would indicate that the AWS Security vulnerability reporting process you're trying to redirect to has already happened and it's now a confirmed issue with a released fix.

Maybe the question from this issue is more simply: Can there be a new release that includes the fixes indicated in [ALAS2KERNEL advisory](https://alas.aws.amazon.com/AL2/ALASKERNEL-5.4-2022-024.html) ?

I completely understand this kind of response for new, undiscovered issues because AWS has an established process but that's not the case for this issue.
