### ISSUE TITLE
latest AMI  Release is having ALASKERNEL-5.10-2022-xxx and ALAS-2022-1581 VULNERABILITIES.

### ISSUE THREAD

**Issue by khushboo121** [awslabs/amazon-eks-ami#913]
Recently we  have create AMI for EKS 1.21 and found the following VULNERABILITIES:

VULNERABILITIES
Amazon Linux 2 : kernel (ALASKERNEL-5.10-2022-XXX): Run 'yum update kernel' to update your system.

Amazon Linux AMI : kernel (ALAS-2022-1581): Run 'yum update kernel' to update your system.

Try running 'yum update kernel' but no package to update:
```
yum update kernel
Loaded plugins: priorities, update-motd, versionlock
amzn2-core                                                                                                                                                                   | 3.7 kB  00:00:00
influxdb                                                                                                                                                                     | 2.5 kB  00:00:00
No packages marked for update
```
**Environment**: ALL
- AWS Region: ALL
- Instance Type(s): x86
- EKS Platform version : 1.21
- Kubernetes version : 1.21
- AMI Version: 1.21
- Kernel (e.g. `uname -a`): 5.4.188-104.359.amzn2.x86_64
- Release information (run `cat /etc/eks/release` on a node):
```
BASE_AMI_ID="ami-****"
BUILD_TIME="Fri May  6 06:44:04 UTC 2022"
BUILD_KERNEL="5.4.188-104.359.amzn2.x86_64"
ARCH="x86_64"
```

**Comment by cartermckinnon** [comment]
The relevant security bulletin for the EKS AMI is [ALASKERNEL-5.4-2022-025](https://alas.aws.amazon.com/AL2/ALASKERNEL-5.4-2022-025.html). The fixes have been present in the EKS AMI since [v20220420](https://github.com/awslabs/amazon-eks-ami/releases/tag/v20220420).

We do not ship an AMI that contains the 5.10 kernel, so `ALASKERNEL-5.10-*` does not apply; and we no longer ship an AMI running* the 4.14 kernel (since the deprecation of Kubernetes 1.18), meaning `ALAS-2022-1581` also does not apply.

*I recently merged a PR (#919) that removed unused kernel versions from the AMI, which were present as a result of a kernel upgrade during the build process. This change will be released in the next AMI later this week, and should alleviate false-positives from scanning tools in the future.
