### ISSUE TITLE
Add c6id and m6id family

### ISSUE THREAD

**Issue by rwilliams-r7** [awslabs/amazon-eks-ami#942]
**What would you like to be added**:
Could you add the c6id and m6id family into https://github.com/aws/amazon-vpc-cni-k8s/blob/master/misc/eni-max-pods.txt

**Why is this needed**:

So we can use c6id and m6id families. A side note when they have not been listed here this causes problems with Karpeneter as it picks those instance types and cannot use them.

**Comment by rwilliams-r7** [comment]
https://github.com/aws/karpenter/issues/1911 -> feature for Karpeneter for referenece.

**Comment by suket22** [comment]
Hey - the file you've linked to is in the AWS VPC CNI. Having said that, both the VPC CNI and the EKS-optimized AL2 AMI attempt to auto-discover parameters about an unknown instanceType through the EC2 API which should've worked for the c6id and m6id family. 

I'll try and update the file regardless, since that ensures there's one less EC2 call during node boot up :)

**Comment by sidewinder12s** [comment]
Ya, that was my understanding was auto-discover should work now (fairly recently) but the file reduces API calls on boot which matters a lot at scale.

**Comment by suket22** [comment]
Yup, we intend on the auto-discovery to only exist as a fallback mechanism so older AMIs work with new instanceTypes. We will continue to keep the `eni-max-pods.txt` file on our AMIs updated. I'll send a PR for this today.

The end goal is that with IPV6 and Prefix Delegation, maxPods isn't something we need to configure on our kubelets at all, and we rely on the 110 default + pod requests to define pod densities.
