### ISSUE TITLE
Allow Horizontal Pod Autoscaler configurations in Controller Manager

### ISSUE THREAD

**Issue by mohitreddy1996** [awslabs/amazon-eks-ami#962]
**What would you like to be added**: Allow configuring Kube Controller Manager, specifically we interested in configuring `horizontal-pod-autoscaler-sync-period` which in kubernetes defaults to 15s 

**Why is this needed**: Our system relies on horizontal pod autoscaler to scale in/out our servers based on CPU and Memory utilization. Due to different traffic patterns, 15s of sync period turns out to be a bit longer for us. We would like to configure it lower than that. It would be great if this is something which is allowed to configure on EKS

**Comment by cartermckinnon** [comment]
This repository is focused on the EKS-optimized node AMI; please open an issue (or +1 an existing one) on https://github.com/aws/containers-roadmap.

(I'm not able to transfer the issue for you because that repo is in a different GitHub org, sorry)

**Comment by HristoStoyanovYotpo** [comment]
Hey, I just wanted to add to this feature request, that we also would like to be able to modify  --concurrent-horizontal-pod-autoscaler-syncs parameter, so that HPA can evaluate metrics more frequently (using higher concurrency). We understand starting from EKS 1.30 this value is dynamically increased based on the size of the managed control-plane, but we still think we may need higher concurrency setting. We would suggest you to introduce EKS Parameter Groups (similarly as RDS ones), so that customers can override control-plane configuration based on their needs!
